I18N_and_commands/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = i18n_patterns(
    path('', include('store.urls', namespace="store")),
    path('order/', include('order.urls', namespace="order")),
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls', namespace="user")),
    prefix_default_language=True
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n"))
]

order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path("cart/", views.CartView.as_view(), name="cart"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("add_to_cart/", views.AddToCartView.as_view(), name="add_to_cart"),
    path("delete/<int:pk>/", views.AddToCartDeleteView.as_view(), name="delete_from_cart")
]

user/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


app_name="user"
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegistrationView.as_view(), name='register'),
]

templates/cart/base_cart.html
{% extends 'base.html' %}
{% load i18n %}
{% comment %}
extends from base.html changes the title and navbar's active page.
has block content for header hero and features. After that goes the
cartcontent which is in the cart.html.
{% endcomment %}

{% block title %}
    Cart
{% endblock %}

{% block content %}
    {% block header %}
        <!-- Single Page Header start -->
        <div class="container-fluid page-header py-5">
            <h1 class="text-center text-white display-6">{% translate "კალათა" %}</h1>
            <ol class="breadcrumb justify-content-center mb-0">
                <li class="breadcrumb-item"><a href="#">{% translate "მთავარი" %}</a></li>
                <li class="breadcrumb-item active text-white">{% translate "კალათა" %}</li>
            </ol>
        </div>
        <!-- Single Page Header End -->
    {% endblock header %}
    {% block cartcontent %}

    {% endblock cartcontent %}
{% endblock content %}

templates/cart/cart-total.html
{% load i18n %}
<div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
    <div class="bg-light rounded">
        <div class="p-4">
            <h1 class="display-6 mb-4"><span class="fw-normal">{% translate "ჯამი" %}</span></h1>
            <div class="d-flex justify-content-between mb-4">
                <h5 class="mb-0 me-4">{% translate "საბტოტალი" %}:</h5>
                <p class="mb-0">${{ subtotal }}</p>
            </div>
            <div class="d-flex justify-content-between">
                <h5 class="mb-0 me-4">{% translate "შიფინგი" %}</h5>
                <div class="">
                    <p class="mb-0">{% translate "მიტანა" %}: ${{ flat_rate }}</p>
                </div>
            </div>
        </div>
        <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
            <h5 class="mb-0 ps-4 me-4">{% translate "ჯამი" %}</h5>
            <p class="mb-0 pe-4">${{ total }}</p>
        </div>
        <button class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4"
                type="button">
            <a href="{% url "order:checkout" %}">{% translate "გააფორმე შეკვეთა" %}</a>
        </button>
    </div>
</div>

templates/cart/cart.html
{% extends 'cart/base_cart.html' %}

{% block nav %}
    {% include 'reusable_components/nav.html' with cart="active" %}
{% endblock nav %}

{% block cartcontent %}
    {% load static %}
    <!-- Cart Page Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    {% include 'cart/table_headers.html' %}
                    </thead>
                    <tbody>
                    {% include 'cart/cartitem.html' %}
                    </tbody>
                </table>
            </div>

{#            <div class="mt-5">#}
{#                <input type="text" class="border-0 border-bottom rounded me-5 py-3 mb-4" placeholder="Coupon Code">#}
{#                <button class="btn border-secondary rounded-pill px-4 py-3 text-primary" type="button">Apply Coupon#}
{#                </button>#}
{#            </div>#}

            <div class="row g-4 justify-content-end">
                <div class="col-8"></div>
                {% include 'cart/cart-total.html'%}
            </div>
        </div>
    </div>
    <!-- Cart Page End -->
{% endblock cartcontent %}

templates/cart/cartitem.html
{% load static %}
{% for cart_item in cart_items %}
    <form action="{% url "order:delete_from_cart" cart_item.id %}" method="POST">
        {% csrf_token %}
        <tr>
            <th scope="row">
                <div class="d-flex align-items-center">
                    <img src="{{ cart_item.product.product_image.crop.80x80 }}" class="img-fluid me-5 rounded-circle"
                         style="width: 80px; height: 80px;" alt="">
                </div>
            </th>
            <td>
                <p class="mb-0 mt-4">{{ cart_item.product.product_name }}</p>
            </td>
            <td>
                <p class="mb-0 mt-4">{{ cart_item.product.product_price }}$</p>
            </td>
            <td>
                <div class="input-group quantity mt-4" style="width: 100px;">
                    <input type="text" name="quantity" class="form-control form-control-sm text-center border-0"
                           value={{ cart_item.product_quantity }}>
                </div>
            </td>
            <td>
                <p class="mb-0 mt-4">{{ cart_item.total_price }}$</p>
            </td>
            <td>
                <input type="hidden" name="product" value="{{ cart_item.product.id }}">
                <button type="submit" value="Delete" class="btn btn-md rounded-circle bg-light border mt-4">
                    <i class="fa fa-times text-danger"></i>
                </button>
            </td>
        </tr>
    </form>
{% endfor %}

templates/cart/table_headers.html
{% load i18n %}
<tr>
    <th scope="col">{% translate "პროდუქტები" %}</th>
    <th scope="col">{% translate "სახელი" %}</th>
    <th scope="col">{% translate "ფასი" %}</th>
    <th scope="col">{% translate "რაოდენობა" %}</th>
    <th scope="col">{% translate "ჯამი" %}</th>
    <th scope="col">{% translate "წაშალე" %}</th>
</tr>