I18N_and_commands/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = i18n_patterns(
    path('', include('store.urls', namespace="store")),
    path('order/', include('order.urls', namespace="order")),
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls', namespace="user")),
    prefix_default_language=True
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n"))
]

order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path("cart/", views.CartView.as_view(), name="cart"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("add_to_cart/", views.AddToCartView.as_view(), name="add_to_cart"),
    path("delete/<int:pk>/", views.AddToCartDeleteView.as_view(), name="delete_from_cart")
]

store/urls.py
from django.urls import path
from . import views


app_name="store"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("category/", views.CategoryListingsView.as_view(), name="category_listings"),
    path("category/<slug:slug>/", views.CategoryListingsView.as_view(), name="category_listings"),
    path("product/<slug:slug>/", views.ProductView.as_view(), name="product"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("test500/", views.InternalServerError.as_view(), name="internal_server_error")
]

user/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


app_name="user"
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegistrationView.as_view(), name='register'),
]

templates/shop/banner.html
{% load static %}
<div>
    <div class="position-relative">
        <img src="{% static 'img/banner-fruits.jpg' %}" class="img-fluid w-100 rounded" alt="">
        <div class="position-absolute"
             style="top: 50%; right: 10px; transform: translateY(-50%);">
            <h3 class="text-secondary fw-bold">Fresh <br> Fruits <br> Banner</h3>
        </div>
    </div>
</div>

templates/shop/base_shop.html
{% extends 'base.html' %}
{% load i18n %}
{% comment %}
extends from base.html changes the title and navbar's active page.
has block content for header hero and features. After that goes the
shopcontent which is in the shop.html.
{% endcomment %}

{% block title %}
    Shop
{% endblock %}

{% block nav %}
    {% include 'reusable_components/nav.html' %}
{% endblock nav %}

{% block content %}
    {% block header %}
    <!-- Single Page Header start -->
    <div class="container-fluid page-header py-5">
        <h1 class="text-center text-white display-6">{% translate "მაღაზია" %}</h1>
        <ol class="breadcrumb justify-content-center mb-0">
            <li class="breadcrumb-item"><a href="{% url "store:index" %}">{% translate "მთავარი" %}</a></li>
            <li class="breadcrumb-item active text-white">{% translate "მაღაზია" %}</li>
        </ol>
    </div>
    <!-- Single Page Header End -->

    {% endblock header %}
    {% block shopcontent %}

    {% endblock shopcontent %}
{% endblock content %}

templates/shop/category.html
{% load i18n %}
<div>
    <div>
        <div class="mb-3">
            <h4>{% translate "კატეგორიები" %}</h4>
            <ul class="list-unstyled fruite-categorie">
                {% for category in categories %}
                    <li>
                        <div class="d-flex justify-content-between fruite-name">
                            <a href="{% url 'store:category_listings' category.slug %}"><i
                                    class="fas fa-apple-alt me-2"></i>{{ category.category_name }}</a>
                            <span>({{ category.count }})</span>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/shop/form.html
{% load i18n %}
<form action="." method="GET" style="width: 324px; display: inline-block">
    <div>
        <div class="input-group w-100 mx-auto d-flex">
            <input type="search" name="q" class="form-control p-3" placeholder="{% translate "მოძებნე" %}"
                   aria-describedby="search-icon-1">
            <button type="submit" id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i>
            </button>
        </div>
    </div>
    {% include 'shop/category.html' %}

    <div>
        <div>
            <div class="mb-3">
                <h4 class="mb-2">{% translate "ფასი" %}</h4>
                <input type="range" name="p" class="form-range w-100" id="rangeInput"
                       min="0" max="100" oninput="amount.value=p.value" value={{ p.value }}>
                <output id="amount" name="amount" min-velue="0" max-value="100" for="rangeInput">0
                </output>
            </div>
        </div>
        <div>
            <div class="mb-3">
                <h4>{% translate "დამატებითი" %}</h4>
                {% for tag in product_tags %}
                    <div class="mb-2">
                        <input type="radio" name="t" class="me-2" id="Categories-1" name="Categories-1"
                               value="{{ tag.id }}">
                        <label for="Categories-3">{{ tag.tag_name }}</label>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div style="margin-top: 20px">
            <div class="bg-light ps-3 py-3 rounded d-flex justify-content-between mb-4">
                <label for="fruits">{% translate "სორტირება" %} :</label>
                <select id="fruits" name="fruitlist" class="border-0 form-select-sm bg-light me-3">
                    <option name="nothing" value="1" {% if param.fruitlist == "1" %}selected{% endif %}>{% translate "არაფერი" %}
                    </option>
                    <option name="price" value="2" {% if param.fruitlist == "2" %}selected{% endif %}>{% translate "ფასის მიხედვით" %}
                    </option>
                </select>
            </div>
        </div>
        <div class="d-flex justify-content-center my-4">
            <button type="submit"
                    class="btn border border-secondary px-4 py-3 rounded-pill text-primary w-100">
                {% translate "გაფილტრე" %}
            </button>
        </div>


        {% include 'shop/banner.html' %}

    </div>
</form>

templates/shop/pagination.html
{% load pagination_filtering %}
<div class="col-12">
    <div class="pagination d-flex justify-content-center mt-5">
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}{% filtered_url fruitlist=param.fruitlist q=param.q p=param.p t=param.t %}" class="rounded">&laquo;</a>
        {% endif %}
        {% for page_num in paginator.page_range %}
            {% if page_obj.number == page_num %}
                <a href="?page={{ page_num }}{% filtered_url fruitlist=param.fruitlist q=param.q p=param.p t=param.t %}" class="rounded active">{{ page_num }}</a>
            {% else %}
                <a href="?page={{ page_num }}{% filtered_url fruitlist=param.fruitlist q=param.q p=param.p t=param.t %}" class="rounded">{{ page_num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}{% filtered_url fruitlist=param.fruitlist q=param.q p=param.p t=param.t %}" class="rounded">&raquo;</a>
        {% endif %}

    </div>
</div>

templates/shop/product.html
{% load static %}
{% load i18n %}
<div class="col-md-6 col-lg-6 col-xl-4">
    <a href="{% url "store:product" product.slug %}">
        <div class="rounded position-relative fruite-item">
            <div class="fruite-img">
                <img src="{{ product.product_image.crop.306x214 }}" class="img-fluid w-100 rounded-top"
                     alt="">
            </div>
            {% if product.tags.all is not None %}
                {% for tag in product.tags.all %}
                    <div class="text-white bg-secondary px-3 py-1 rounded position-absolute"
                         style="top: 10px; left: 10px;">{{ tag.tag_name }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                <form action="{% url "order:add_to_cart" %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="product" value="{{ product.id }}">
                    <input type="hidden" name="product_quantity" value="1">
                    <h4>{{ product.product_name }}</h4>
                    <p>{{ product_description }}</p>
                    <div class="d-flex justify-content-between flex-lg-wrap">
                        <p class="text-dark fs-5 fw-bold mb-0">{% translate "ლ" %}{{ product.product_price }} / {% translate "კგ" %}</p>
                        <button type="submit" class="btn border border-secondary rounded-pill px-3 text-primary"><i
                                class="fa fa-shopping-bag me-2 text-primary"></i>{% translate "დაამატე კალათაში" %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </a>
</div>

templates/shop/shop.html
{% extends 'shop/base_shop.html' %}
{% load static %}
{% load i18n %}
{% block shopcontent %}
    {# shop start #}
    <div class="container-fluid fruite py-5">
        <div class="container py-5">
            <h1 class="mb-4">{% translate "ახალი ხილ-ბოსტნეულის მაღაზია" %}</h1>

            <div class="row g-4">
                {% include 'shop/form.html' %}
                <div class="col-lg-9">
                    <div class="row g-4 justify-content-center">
                        {% for product in object_list %}
                            {% include 'shop/product.html' %}
                        {% endfor %}
                    </div>
                    {% include 'shop/pagination.html' %}
                </div>
            </div>
        </div>
    </div>
    {# shop end #}

{% endblock shopcontent %}