I18N_and_commands/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = i18n_patterns(
    path('', include('store.urls', namespace="store")),
    path('order/', include('order.urls', namespace="order")),
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls', namespace="user")),
    prefix_default_language=True
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n"))
]

order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path("cart/", views.CartView.as_view(), name="cart"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("add_to_cart/", views.AddToCartView.as_view(), name="add_to_cart"),
    path("delete/<int:pk>/", views.AddToCartDeleteView.as_view(), name="delete_from_cart")
]

store/urls.py
from django.urls import path
from . import views


app_name="store"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("category/", views.CategoryListingsView.as_view(), name="category_listings"),
    path("category/<slug:slug>/", views.CategoryListingsView.as_view(), name="category_listings"),
    path("product/<slug:slug>/", views.ProductView.as_view(), name="product"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("test500/", views.InternalServerError.as_view(), name="internal_server_error")
]

user/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


app_name="user"
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegistrationView.as_view(), name='register'),
]

templates/reusable_components/modal-search.html
<form action="." method="GET">
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center">
                <div class="input-group w-75 mx-auto d-flex">
                    <input name="q" type="search" class="form-control p-3" placeholder="keywords"
                           aria-describedby="search-icon-1">
                    <button type="submit" id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

templates/reusable_components/nav.html
{% load cache %}
{% load i18n %}
{% block nav %}
    <div class="container-fluid fixed-top">
        <div class="container topbar bg-primary d-none d-lg-block">
            <div class="d-flex justify-content-between">
                <div class="top-info ps-2">
                    <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#"
                                                                                                     class="text-white">123
                        Street, New York</a></small>
                    <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#"
                                                                                              class="text-white">Email@Example.com</a></small>
                </div>
                <div class="top-link pe-2">
                    <a href="#" class="text-white"><small class="text-white mx-2">Privacy Policy</small>/</a>
                    <a href="#" class="text-white"><small class="text-white mx-2">Terms of Use</small>/</a>
                    <a href="#" class="text-white"><small class="text-white ms-2">Sales and Refunds</small></a>
                </div>

                <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <select class="for_lang_select" name="language">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option class="for_lang_option" value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                    selected{% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}
                    </select>
                    <button class="for_lang" type="submit" value="switch">{% translate "შეცვლა" %}</button>
                </form>
            </div>
        </div>
        <div class="container px-0">
            <nav class="navbar navbar-light bg-white navbar-expand-xl">
                <a href="{% url 'store:index' %}" class="navbar-brand"><h1 class="text-primary display-6">
                    Fruitables</h1></a>
                <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars text-primary"></span>
                </button>
                <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% cache 60 navbar LANGUAGE_CODE %}
                        <div class="navbar-nav mx-auto">
                            <a href="{% url 'store:index' %}" class="nav-item nav-link">{% translate "მთავარი" %}</a>
                            <a href="{% url 'store:category_listings' %}"
                               class="nav-item nav-link">{% translate "მაღაზია" %}</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle"
                                   data-bs-toggle="dropdown">{% translate "კატეგორიები" %}</a>
                                <div class="dropdown-menu m-0 bg-secondary rounded-0">
                                    {% for category in categories_root %}
                                        <a href="{% url 'store:category_listings' category.slug %}"
                                           class="dropdown-item ">{{ category.category_name }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                            <a href="{% url 'store:contact' %}" class="nav-item nav-link">{% translate "კონტაქტი" %}</a>
                        </div>
                    {% endcache navbar %}

                    <div class="d-flex m-3 me-0">
                        <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4"
                                data-bs-toggle="modal" data-bs-target="#searchModal"><i
                                class="fas fa-search text-primary"></i></button>
                        <a href="{% url 'order:cart' %}" class="position-relative me-4 my-auto">
                            <i class="fa fa-shopping-bag fa-2x"></i>
                            <span class="position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1"
                                  style="top: -5px; left: 15px; height: 20px; min-width: 20px;">{{ cart_count }}</span>
                        </a>
                        <a href="{% url 'user:login' %}" class="my-auto">
                            <i class="fas fa-user fa-2x"></i>
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>

{% endblock nav %}

templates/reusable_components/spinner.html
<div id="spinner"
     class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
    <div class="spinner-grow text-primary" role="status"></div>
</div>